# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-canary
  namespace: dev
  labels:
    app: nginx-deployment-canary
spec:
  replicas: 1
  selector:
    matchLabels: # Must keep consistent with template.metadata.labels
      app: nginx 
  template:
    metadata:
      labels:
        app: nginx # This label is same as service' selector, so it will be added into service automatically
        track: canary
    spec:
      containers:
      - name: new-nginx
        image: docker/getting-started
        ports:
        - containerPort: 80